version: '3.8'
services:
  neo4j:
    image: neo4j:4.4.3-community
    ports:
      - 7999:7474
      - 7000:7687
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/0900pass
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins
  api:
    build: .
    container_name: "PerfectPick_Likes_ms"
    ports:
      - 3000:3000
    depends_on:
      - neo4j
